/**
 ****************************************************************************************
 *
 * @file crc16.c
 *
 * @brief crc16 table & crc calculation function.
 *
 * Copyright (C) Quintic 2014-2014
 *
 * $Rev: 5338 $
 *
 ****************************************************************************************
 */

/*
 * INCLUDE FILES
 ****************************************************************************************
 */
 
#include "crc16.h"


/*
 * GLOBAL VARIABLE DEFINITIONS
 ****************************************************************************************
 */

/*the following crc table is generated by  CRC-CCITT = X16 + X12 + X5 + X0 */
const uint16_t crc16_table[256] =
{
 0X0000,  0X1021,  0X2042,  0X3063,  
 0X4084,  0X50a5,  0X60c6,  0X70e7,  
 0X8108,  0X9129,  0Xa14a,  0Xb16b,  
 0Xc18c,  0Xd1ad,  0Xe1ce,  0Xf1ef,  
 0X1231,  0X0210,  0X3273,  0X2252,  
 0X52b5,  0X4294,  0X72f7,  0X62d6,  
 0X9339,  0X8318,  0Xb37b,  0Xa35a,  
 0Xd3bd,  0Xc39c,  0Xf3ff,  0Xe3de,  
 0X2462,  0X3443,  0X0420,  0X1401,  
 0X64e6,  0X74c7,  0X44a4,  0X5485,
 0Xa56a,  0Xb54b,  0X8528,  0X9509,  
 0Xe5ee,  0Xf5cf,  0Xc5ac,  0Xd58d,  
 0X3653,  0X2672,  0X1611,  0X0630,  
 0X76d7,  0X66f6,  0X5695,  0X46b4,  
 0Xb75b,  0Xa77a,  0X9719,  0X8738,  
 0Xf7df,  0Xe7fe,  0Xd79d,  0Xc7bc,  
 0X48c4,  0X58e5,  0X6886,  0X78a7,  
 0X0840,  0X1861,  0X2802,  0X3823,  
 0Xc9cc,  0Xd9ed,  0Xe98e,  0Xf9af,  
 0X8948,  0X9969,  0Xa90a,  0Xb92b,  
 0X5af5,  0X4ad4,  0X7ab7,  0X6a96,  
 0X1a71,  0X0a50,  0X3a33,  0X2a12,  
 0Xdbfd,  0Xcbdc,  0Xfbbf,  0Xeb9e,  
 0X9b79,  0X8b58,  0Xbb3b,  0Xab1a,  
 0X6ca6,  0X7c87,  0X4ce4,  0X5cc5,  
 0X2c22,  0X3c03,  0X0c60,  0X1c41,  
 0Xedae,  0Xfd8f,  0Xcdec,  0Xddcd,
 0Xad2a,  0Xbd0b,  0X8d68,  0X9d49,  
 0X7e97,  0X6eb6,  0X5ed5,  0X4ef4,  
 0X3e13,  0X2e32,  0X1e51,  0X0e70,  
 0Xff9f,  0Xefbe,  0Xdfdd,  0Xcffc,  
 0Xbf1b,  0Xaf3a,  0X9f59,  0X8f78,  
 0X9188,  0X81a9,  0Xb1ca,  0Xa1eb,  
 0Xd10c,  0Xc12d,  0Xf14e,  0Xe16f,  
 0X1080,  0X00a1,  0X30c2,  0X20e3,  
 0X5004,  0X4025,  0X7046,  0X6067,  
 0X83b9,  0X9398,  0Xa3fb,  0Xb3da,  
 0Xc33d,  0Xd31c,  0Xe37f,  0Xf35e,  
 0X02b1,  0X1290,  0X22f3,  0X32d2,  
 0X4235,  0X5214,  0X6277,  0X7256,  
 0Xb5ea,  0Xa5cb,  0X95a8,  0X8589,  
 0Xf56e,  0Xe54f,  0Xd52c,  0Xc50d,  
 0X34e2,  0X24c3,  0X14a0,  0X0481,  
 0X7466,  0X6447,  0X5424,  0X4405,
 0Xa7db,  0Xb7fa,  0X8799,  0X97b8,  
 0Xe75f,  0Xf77e,  0Xc71d,  0Xd73c,  
 0X26d3,  0X36f2,  0X0691,  0X16b0,  
 0X6657,  0X7676,  0X4615,  0X5634,  
 0Xd94c,  0Xc96d,  0Xf90e,  0Xe92f,  
 0X99c8,  0X89e9,  0Xb98a,  0Xa9ab,  
 0X5844,  0X4865,  0X7806,  0X6827,  
 0X18c0,  0X08e1,  0X3882,  0X28a3,  
 0Xcb7d,  0Xdb5c,  0Xeb3f,  0Xfb1e,  
 0X8bf9,  0X9bd8,  0Xabbb,  0Xbb9a,  
 0X4a75,  0X5a54,  0X6a37,  0X7a16,  
 0X0af1,  0X1ad0,  0X2ab3,  0X3a92,  
 0Xfd2e,  0Xed0f,  0Xdd6c,  0Xcd4d,  
 0Xbdaa,  0Xad8b,  0X9de8,  0X8dc9,  
 0X7c26,  0X6c07,  0X5c64,  0X4c45,  
 0X3ca2,  0X2c83,  0X1ce0,  0X0cc1,  
 0Xef1f,  0Xff3e,  0Xcf5d,  0Xdf7c,
 0Xaf9b,  0Xbfba,  0X8fd9,  0X9ff8,  
 0X6e17,  0X7e36,  0X4e55,  0X5e74,  
 0X2e93,  0X3eb2,  0X0ed1,  0X1ef0
};


/*
 * FUNCTION DEFINITIONS
 ****************************************************************************************
 */

/**
 ****************************************************************************************
 * @brief CRC16 calculation (X16 + X12 + X5 + X0)
 *
 * @param[in] p_data    Start address of data
 * @param[in] size      Data size
 *
 * @return Result of CRC16
 ****************************************************************************************
 */

uint16_t crc16(uint8_t * p_data, uint32_t size)
{
    uint16_t crc16 = 0;
    
    for (uint32_t i=0; i < size; i++ )
        crc16 = ( crc16 << 8 ) ^ ( unsigned short )crc16_table[( crc16 >> 8 ) ^ *p_data++];

    return crc16;
}


